// GENERATED FILE — do not edit by hand.
//
// Source of truth: /home/mm/builds/the-shade/THE-SHADE-NOVEL.md
// Regenerate with: node extract-chapters.mjs
//
// Reading order interleaves the three timelines: T1-Ch1, T2-Ch1, T3-Ch1, T1-Ch2, ...

export const timelines = [
  {
    "id": 1,
    "name": "The Race",
    "color": "#ff6b4a",
    "blurb": "Near future. An asteroid is detected, and the race to escape begins — until the escape itself becomes the disaster.",
    "planned": 20,
    "written": 4
  },
  {
    "id": 2,
    "name": "The Bunker",
    "color": "#4a9eff",
    "blurb": "Years after the Shade. Survivors underground keep a reactor alive and send expeditions into the dark.",
    "planned": 20,
    "written": 4
  },
  {
    "id": 3,
    "name": "The Floating City",
    "color": "#ffd24a",
    "blurb": "Concurrent with the bunker. A city of boats survives inside the one patch of sunlight left on Earth.",
    "planned": 20,
    "written": 4
  }
]

export const chapters = [
  {
    "id": 1,
    "timeline": 1,
    "timelineName": "The Race",
    "chapterNumber": 1,
    "title": "The Signal",
    "setting": "Near future — Earth races to escape",
    "wordCount": 435,
    "paragraphs": [
      "The dust hung in the server room air. Amara Okafor wiped sweat from her forehead, left a streak of thermal paste across her temple. The cooling system had failed again. Sixteen hours into the shift and the Helios Array simulation still wouldn't converge.",
      "Her terminal blinked. Priority alert. She almost ignored it—another false alarm, another asteroid that would miss by comfortable margins. But the encryption signature was wrong. Observatory-direct. She opened it.",
      "2034-Prometheus. Impact probability: 94.7%. Time to collision: 47 months.",
      "The numbers sat there. Clean. Certain. She ran the trajectory three times. Each iteration tightened the certainty. The asteroid measured 2.4 kilometers across. Strike point: North Atlantic. The simulation showed the pressure wave, the tsunami, the dust cloud that would follow.",
      "Her hands shook. She reached for the phone, stopped. Who to call first? Her supervisor worked for Garrett Voss. Exodus Solutions funded this lab, owned the Helios Array, owned her research. The man who'd promised to save humanity would want this first.",
      "The server fans screamed. One failed. Then another. The room temperature spiked. Amara barely noticed.",
      "Outside the lab window, the city kept moving. Cars threaded through traffic. Someone walked a dog. The sun hung in a sky that would soon fill with enough debris to end most life on the surface.",
      "She thought: I built salvation. The Array could power the evacuation ships, capture and store solar energy for the colonies we'd build in orbit and beyond. Four years of my life. But Garrett controls it.",
      "The phone rang. She hadn't called anyone yet. The screen showed: UNKNOWN.",
      "She answered.",
      "\"Dr. Okafor.\" A woman's voice, flat affect. \"You have the trajectory data.\"",
      "\"Who is this?\"",
      "\"Someone who knows what Garrett Voss plans to do with your Array. And what you need to do to stop him.\"",
      "The line went dead.",
      "Through the window, a military helicopter crossed the skyline. Then another. Already? The data wasn't public yet. How long had they known?",
      "Amara looked at her screen. The Helios Array blueprint, three years of engineering compressed into lines and equations. Meant to save everyone. But Garrett would save only those who could pay.",
      "Her terminal chimed. Email from Garrett's office: Emergency board meeting, 0600 tomorrow. Attendance mandatory.",
      "She thought about the caller. About stopping Garrett. She'd built the Array believing in its purpose. Now she had to decide: trust the man who paid for it, or the stranger who warned her?",
      "The last server fan died. Red lights across the board. In four years, none of this would matter. The rock was coming. Everything else was just the scramble before impact."
    ]
  },
  {
    "id": 2,
    "timeline": 2,
    "timelineName": "The Bunker",
    "chapterNumber": 1,
    "title": "Ten Years Down",
    "setting": "Years after the Shade — survivors underground",
    "wordCount": 423,
    "paragraphs": [
      "Kira walks the morning count. Hallway C, fifteen doors. Thirteen occupied. She knocks: two slow, one fast. Waits for the knock back. At C-7 no answer. She knocks again. Counts thirty seconds by her pulse. The door opens. Fahim's eyes are red-rimmed, but he's standing. That's what matters. She marks the tally sheet and moves on. Overhead, the fluorescent hums its endless note.",
      "Ten years since the Shade fell. The bunker marks time in reactor cycles and shift rotations. Morning is when the lights come up. Night is when they dim to emergency levels. The sun is a story Eugene tells to children who've never seen it.",
      "Dr. Amara Voss checks the reactor gauges. Coolant temperature steady. Pressure nominal. The nuclear plant was meant to power a launch facility for five years. They've stretched it to ten. Every year she finds new ways to cannibalize non-essential systems. Every year the margin shrinks.",
      "The hydroponic bay smells like growth and rot together. Lia Oshan tends the tomato vines, checking each plant for blight. Seventeen and she's never tasted fruit grown in soil. Never felt rain. The garden feeds two hundred people on a rotation of greens and root vegetables. When a crop fails, people go hungry. No one complains. Complaining uses energy.",
      "Maya Strand calls the council meeting for 0800. Same room, same faces, same arguments worn smooth by repetition. The expedition lottery is next week. Four people will suit up, take thermal gear and emergency rations, and walk into the frozen dark for four hours. The protocol is strict: stay within beacon radius, return before core temperature drops below 35 Celsius. Three expeditions this year. Three times they've returned with nothing.",
      "Kade Oshan wants to push farther. His daughter hasn't seen the sky. He'll die trying to find it.",
      "Eugene Pryce remembers the before. Shuttle technician, sixty years old when the Shade fell. Now seventy-one and his memory frays at the edges. Sometimes he confuses yesterday with a decade ago. But he remembers the launch facility, the corridors that run beyond the bunker's sealed sections. Old maps folded in his quarters. He spreads them for anyone who'll listen.",
      "The reactor hums. The lights flicker once, stabilize. Another day in the bunker. Another count. Another shift. The world outside is −60 Celsius and absolute dark. Inside, the walls are close and warm and certain. Some call it survival. Others call it a tomb they haven't finished dying in.",
      "Kade watches his daughter in the garden and thinks: there has to be more than this."
    ]
  },
  {
    "id": 3,
    "timeline": 3,
    "timelineName": "The Floating City",
    "chapterNumber": 1,
    "title": "Harbor of Boats",
    "setting": "Concurrent — life inside the sunlight patch",
    "wordCount": 443,
    "paragraphs": [
      "Mira surveys the floating city at dawn. The sun rises over water that reflects gold and orange, and for a moment she forgets how small their refuge is. Sixty boats lashed together, makeshift platforms bridging the gaps. Five hundred people living on what used to be personal watercraft, fishing vessels, a houseboat cluster, two cargo barges. They've added structures—bamboo frames, salvaged aluminum, rope bridges strung between hulls.",
      "The geostationary patch sits over deep ocean. Forty kilometers of open water lit by sun while the rest of the planet freezes in perpetual twilight. They were lucky. Or doomed to watch the light shrink while they cling to it.",
      "She climbs to the highest platform. Kael's construction, built from shipping containers welded to the central barge. From here she can see the whole city: the eastern fishing cluster, the western living quarters, the central market where people trade catch for repairs. Beyond, the water darkens. The edge of the light.",
      "Nets go out with the morning. Yorke watches from her solar platform, checking the array output. Mismatched panels salvaged from boats, angled to catch every degree of sun. Power charges batteries for the water purification system, for lights when the sun sets, for tools. She's optimized the arrangement twelve times. Each iteration buys them a few more watt-hours per day.",
      "Kael's daughters help with the nets. Emiko, sixteen, has modified the pulleys with reclaimed bicycle gears. Yuki, fourteen, sketches the fish they catch, building an inventory of what lives in this warm pocket of ocean. Dr. Seo-yun encourages her, teaches her to notice patterns. Which species are thriving, which are disappearing. The water temperature dropped half a degree last month.",
      "Nikos brings in the morning catch. His trawler is the oldest vessel, Greek letters fading on the hull. He's been fishing these waters since the Shade fell, back when they thought rescue would come. Now he teaches younger crews to read currents and weather. The old ways adapted to a new world where the only sky is a circle overhead.",
      "Council meets at noon in Reika's lifeboat. She pours cold tea from a thermal jug, serves it in mismatched cups. The agenda: food stores, water rations, a proposal to expand the platform eastward. Kael wants to build up. Others want to stay low, keep weight distributed. Every decision is about survival measured in stability and fish and sunlight.",
      "The city rocks gently on the swell. At night, bioluminescent plankton glow beneath the boats. Small beauty in a dying ocean. Mira watches the horizon where the light meets dark. Somewhere beyond, the planet freezes. Here, for now, they fish and build and hope the warmth holds."
    ]
  },
  {
    "id": 4,
    "timeline": 1,
    "timelineName": "The Race",
    "chapterNumber": 2,
    "title": "Launch Windows",
    "setting": "Near future — Earth races to escape",
    "wordCount": 751,
    "paragraphs": [
      "The UN General Assembly hall held 193 nations. Garrett Voss counted twelve that mattered.",
      "He sat in the gallery, watching them argue over protocols for joint evacuation. As if protocols would save anyone. The Chinese delegation demanded equal launch capacity. The Americans countered with historical investment figures. The Europeans proposed a lottery system. All of them pretended the math could be democratic.",
      "Launch capacity was finite. The asteroid wasn't.",
      "Garrett's tablet showed the real numbers. Current orbital infrastructure: 940 personnel capacity across all active stations. Launch windows to viable trajectories: 87 in the next 47 months. Each window narrowed as fuel calculations tightened. By month 40, you'd need three times current fuel stocks to reach orbit with enough delta-v to escape the debris field.",
      "He ran the simulation again. Best case, full global cooperation, every spaceport running continuous missions: 12,000 people off-planet before impact. Earth population: 8.3 billion.",
      "Someone had to choose. Garrett preferred it be him rather than some committee that would spend six months debating selection criteria while launch windows closed.",
      "His phone buzzed. Text from Riko: SITUATION BAIKONUR. CALL NOW.",
      "He stepped into the hallway. The call connected before the first ring.",
      "\"Kwame Osei took the Cosmodrome.\" Riko's voice had that clipped quality she used when things had gone badly. \"Four hours ago. His forces came overland, avoided sat coverage. They control the main pad and fuel depot.\"",
      "Garrett felt his pulse level. Stay ahead of the chaos or get swept under. \"Casualties?\"",
      "\"Thirty confirmed. Mostly ground crew. The launch director negotiated a ceasefire.\"",
      "\"Tell me you have forces en route.\"",
      "\"Six hours out. But Kwame's already broadcasting. Says launch capacity is African first, then whoever can pay. He's set up a market.\"",
      "Of course he had. The warlord prophet, turning the apocalypse into a trading floor.",
      "Garrett thought about the Helios Array sitting in Amara's lab. With that operational, he could power ships ten times faster than conventional systems. But the Array was still theoretical. And now Kwame controlled one of the few pads capable of heavy-lift launches.",
      "\"Hold position,\" he told Riko. \"Don't engage until I give the word.\"",
      "\"He's fortifying. Every hour we wait—\"",
      "\"I know. But if we take it by force, the pad gets damaged. We need it intact.\"",
      "He ended the call. Through the window, the UN delegates were voting on a resolution to establish an Evacuation Coordination Committee. Twelve nations had to approve. The vote would take days. By then Kwame would own the primary route to orbit.",
      "Garrett made three calls. The first to his logistics chief: move the Exodus Solutions fleet to staging range of Baikonur. The second to his intel director: find out what Kwame wanted that money couldn't buy. The third to Amara.",
      "\"Dr. Okafor. Have you seen the news from Kazakhstan?\"",
      "\"I saw.\" Her voice carried that controlled anger she used when someone wasted her time. \"What do you want, Garrett?\"",
      "\"How long until the Array is operational?\"",
      "Silence. Then: \"With full funding and no regulatory delays? Eighteen months.\"",
      "\"You have six.\"",
      "\"That's not possible.\"",
      "\"Make it possible. I'll triple your budget, clear every regulatory barrier, and put you in direct control. No board approval needed. But I need that Array working in six months.\"",
      "Another pause. He could almost hear her calculating. \"Why the rush? We have four years before impact.\"",
      "\"Because in four years everyone with a ship will be fighting over fuel. But if I have the Array, I control the energy supply. And whoever controls energy controls who gets off this rock.\"",
      "\"You want me to weaponize my research.\"",
      "\"I want you to save lives. Mine. Yours. Everyone who works for Exodus. We can coordinate a real evacuation, not the chaos that's coming. But only if we move now.\"",
      "He could hear her breathing. The idealist and the pragmatist fighting it out behind her silence.",
      "\"I'll need your head engineer,\" she said finally. \"And complete access to your fabrication facilities.\"",
      "\"Done. I'm sending Riko to escort you to the secure site. Pack for six months.\"",
      "He hung up and looked back through the window at the UN floor. The vote was still going. Procedure grinding forward while the world burned. Some of them would make it off-planet. Garrett would see to that. The rest would learn that survival had never been democratic.",
      "His tablet chimed. News alert: Armed conflict at Baikonur Cosmodrome. At least thirty dead. Kazakh government requests international peacekeeping force.",
      "Too late for peacekeeping. The war for tomorrow had started."
    ]
  },
  {
    "id": 5,
    "timeline": 2,
    "timelineName": "The Bunker",
    "chapterNumber": 2,
    "title": "The Surface Protocol",
    "setting": "Years after the Shade — survivors underground",
    "wordCount": 518,
    "paragraphs": [
      "Marcus suits up in the equipment bay. Thermal gear, oxygen reserve, emergency beacon. The protocol is twenty years old but nobody's improved it. Four hours maximum exposure. Stay within a two-kilometer radius. Return before core temperature drops below 35 Celsius.",
      "He's done this seventeen times. Seventeen expeditions into the frozen dark. Seventeen times he's returned with nothing.",
      "The team assembles: four people, two sleds loaded with gear. Jin checks the beacon calibration. Kade watches from the observation window, his daughter beside him. Lia's never been topside. None of the children born after the Shade have.",
      "Dr. Amara Voss runs through the final checklist. Reactor output stable. Life support nominal. The outer door will cycle in sixty seconds. She marks the departure time on her log.",
      "The door opens. Cold floods in, −62 Celsius, the air crystallizing in visible clouds. Marcus steps through. His headlamp cuts a cone of light through absolute darkness. No stars. No moon. The Shade blocks everything.",
      "The ground is ice over permafrost. His boots crunch. The sled runners scrape. They move northwest, following a heading Jin calculated from old maps. There might be a highway under the ice. There might be nothing.",
      "Two kilometers out, they stop. Jin takes readings. Temperature, wind speed, atmospheric composition. All within expected ranges. The darkness is total beyond their lights. Marcus thinks: somewhere above us, solar panels cover the sky. Somewhere there's a hole with sunlight. But not here.",
      "They find a building. Collapsed roof, walls buckled by ice. They clear the entrance, work their way inside. Storage facility, long abandoned. Shelves empty. No fuel, no food, no equipment worth salvaging.",
      "Back outside, Jin marks the location on his map. Another nothing. Another empty square on the growing chart of the frozen world.",
      "Three hours in, Marcus's core temperature reads 36.1. The protocol is clear: turn back. But there's a ridge to the north, maybe a thermal anomaly, maybe just wind patterns. He wants to check.",
      "Jin shakes his head. The protocol. They turn back.",
      "The bunker door cycles. Warm air, bright lights. They strip the gear, run the decontamination sequence. Amara logs their return. Four hours, twelve minutes. No casualties. No discoveries.",
      "Maya asks for the report at the evening council meeting. Jin spreads his map. Seventeen expeditions, thirty-four sorties, coverage area expanding but still finding nothing. The frozen dark goes on.",
      "Eugene watches from the back. He's been thinking about the launch facility, the parts they sealed off when the population concentrated in the bunker core. There are tunnels. Old service routes. He's got maps, somewhere in his quarters, if he can remember where.",
      "Kade asks about the next lottery. Who goes topside next week. The protocol allows expeditions every seven days, resource recovery permitting.",
      "Lia sits in the hydroponic bay after the meeting. The tomatoes need pruning. The system cycles, water and nutrients flowing through channels, LED arrays providing spectrum. It's all closed-loop, all balanced. It works. But she understands what her father chases: the world outside this metal shell. The sun he talks about. The open air.",
      "She's seventeen. She's never seen a sky."
    ]
  },
  {
    "id": 6,
    "timeline": 3,
    "timelineName": "The Floating City",
    "chapterNumber": 2,
    "title": "The Engineer's Gambit",
    "setting": "Concurrent — life inside the sunlight patch",
    "wordCount": 520,
    "paragraphs": [
      "Yorke climbs the solar platform at first light. The array needs realignment—yesterday's output dropped three percent. Small losses compound. Three percent today means someone goes thirsty tomorrow.",
      "The panels tilt on salvaged hinges, tracking mechanisms jury-rigged from boat winches. She adjusts the western section by hand, checking voltage as she works. The morning sun is perfect, low angle, no clouds in this pocket of sky. But the patch is smaller than last year. She's measured it.",
      "Below, the fishing nets come up. Kael's daughters help haul, Emiko calling out the rhythm. The catch looks thin. Yorke notes it—fish populations correlating with water temperature, temperature dropping monthly. Dr. Seo-yun has the data. Nobody wants to see the trend line.",
      "Council meets at noon. Reika pours tea, serves it in the mis matched cups they've used for three years. The agenda: Taryn's proposal to expand deep-water harvesting.",
      "\"We dismantle the eastern pontoons,\" Taryn says. \"Use the materials for vertical nets. Go deeper where the fish are moving.\"",
      "\"You're asking us to cannibalize the city,\" someone says.",
      "\"I'm asking us to adapt.\"",
      "The debate runs for an hour. Resources versus risk. Stability versus survival. Finally a vote: thirteen for, eight against. The expansion proceeds.",
      "Kael's team starts work the next day. They unbolt aluminum frames, coil the anchor lines, strip the decking. Piece by piece, the eastern edge of the city comes apart. Each beam, each sheet of metal gets marked and inventoried. Everything has two futures: what it was, what it might become.",
      "By evening, a gap opens in the city. Water shows between the remaining platforms. It feels like amputation.",
      "Yorke watches from her solar platform. The math is simple: fewer surface structures means less electrical load. But it also means less living space, less storage, less buffer when storms hit. They're trading stability for food. She hopes the trade is worth it.",
      "Nikos brings his trawler in after dark. He ties off at the central dock, climbs aboard with his catch log. The numbers are down again. Forty kilos today. They need eighty to meet rations.",
      "\"The cold's pushing them deeper,\" he tells Seo-yun. \"Below where we can reach safely.\"",
      "\"Then we learn to reach deeper.\"",
      "\"Or we eat less.\"",
      "That night, Yorke lies in her cabin—a repurposed houseboat room, four meters by three, everything she owns within arm's reach. Through the porthole, she can see the edge of darkness where the light ends. Out there, the planet freezes. Here, for now, the sun holds.",
      "She thinks about the solar array, about the slow decline in output as the patch shrinks. She's extended the system twice, optimized every connection. But you can't engineer around geometry. Less sunlight means less power. Less power means choices she doesn't want to make.",
      "Tomorrow she'll recalibrate. Tomorrow the nets will go deeper. Tomorrow Kael's team will weld the salvaged metal into new structures, building from what they've dismantled. Adapting. Always adapting.",
      "The city rocks on the swell. Somewhere below, in the dark water, fish are moving. Somewhere above, the Shade holds. And in this thin margin between, five hundred people try to hold on."
    ]
  },
  {
    "id": 7,
    "timeline": 1,
    "timelineName": "The Race",
    "chapterNumber": 3,
    "title": "The Pitch",
    "setting": "Near future — Earth races to escape",
    "wordCount": 776,
    "paragraphs": [
      "The helicopter came in low over the lab roof at 0430 and didn't bother to land properly. Amara watched it from the loading bay, arms crossed, while the rotor wash threw grit across four years of her work stacked in crates.",
      "Riko Tanaka came down the ramp first. Short, compact, hair cropped to the skull, sidearm holstered like a tool she used often enough to stop thinking about. She looked at the crates. She looked at Amara. She did not introduce herself.",
      "\"You're not moving the Array,\" Riko said. \"You're moving the drawings.\"",
      "\"The Array is two hundred tonnes of vacuum-deposited graphene and a folding truss that doesn't fit on a helicopter.\"",
      "\"Then we're moving the drawings.\"",
      "Amara had spent the night arguing with herself and had already lost. Six months. Garrett's voice in her ear, patient as a man explaining arithmetic to a child. She had watched the Baikonur footage at 0200 — harvesters burning on the pad, a fuel depot lit up orange, and above it, marginally, the curve of a rocket she had helped design the power system for. Thirty dead on the ground. Two hundred thousand people with tickets they'd bought in a currency that didn't exist yet.",
      "She got in the helicopter. The crates went in the belly.",
      "They flew east for two hours. Below, the suburbs gave way to scrub, the scrub to dry lakebed, the lakebed to nothing. Amara dozed against the bulkhead and woke to the sound of Isaiah Cross on the cabin radio, because Riko had left it on some frequency she'd been told to monitor.",
      "\"—so here's what they're not telling you. Exodus Solutions holds the launch schedule. Exodus Solutions holds the fuel contracts. Exodus Solutions holds the *power*. And power, friends, is the only ticket on the boat.\"",
      "Isaiah Cross had a voice like a man selling used cars in a war zone. Amara had heard him a hundred times and never once believed a word. Now his words had the flat ring of a maintenance manual.",
      "A second voice cut in, patched over the feed. Younger. Angrier. \"This is FreeLight Collective. We're posting the full Helios Array specification to every node we can reach, because the design was funded with public science grants and public money buys public property. Anything that can hold a ship and a person belongs to the people holding the person.\"",
      "\"You've got thirty seconds before they find you,\" Isaiah said, delighted.",
      "\"Then thirty seconds. Exodus is not building a lifeboat. They're building a *gate*. And gates have tolls.\"",
      "The feed dissolved into static. Riko reached over and killed it without looking.",
      "\"Who was that?\" Amara asked.",
      "\"Nobody.\"",
      "\"That was a real person.\"",
      "\"They're all real people.\" Riko checked her watch. \"They're just not the ones who'll matter in forty-seven months.\"",
      "Amara looked at her for a moment. There was nothing in the woman's face to read. Later Amara would understand that this was itself the information.",
      "The site was a fabrication hall sunk into a caldera — a decommissioned test facility Exodus had bought at auction and never announced. Inside, forty technicians were already working. On the floor, in chalk, someone had drawn the outline of the Array's primary truss at full scale. It ran the length of the building and out through a loading door into the desert.",
      "Her team. Somebody had already staffed her team.",
      "She walked the chalk line and hated how good it looked. The evacuation they'd never manage. The corridors she'd written about in grant applications as *orbital agriculture infrastructure*. Chalk on concrete, forty people, and a six-month clock.",
      "\"Dr. Okafor.\"",
      "A young woman stood at the end of the truss, holding a tablet. Twenty-eight, maybe. Lab coat with the sleeves rolled to the elbow. She had the specific, unguarded brightness of someone who had not yet been disappointed by anyone she respected.",
      "\"I'm Yuki Sato. Mr. Voss assigned me as your head engineer.\"",
      "Amara took the tablet. On it was the full specification. Complete. Correct. Better annotated than her own files.",
      "\"You've been reading my work.\"",
      "\"Since the paper. 'Graphene capture efficiency in geostationary flux conditions.'\" Yuki said it the way people say a lyric. \"I built a working simulator off your Methods section. It ran. Nobody else's has.\"",
      "Amara looked down the length of the chalk truss, out the loading door, into the desert where the sun was coming up orange and enormous and doomed.",
      "\"Then you already know what this is,\" Amara said.",
      "Yuki's brightness didn't waver. \"I know what it's for.\"",
      "\"That's not the same thing.\"",
      "\"No,\" Yuki agreed, and went to get her a hard hat. \"It never is.\""
    ]
  },
  {
    "id": 8,
    "timeline": 2,
    "timelineName": "The Bunker",
    "chapterNumber": 3,
    "title": "Names in a Tin",
    "setting": "Years after the Shade — survivors underground",
    "wordCount": 670,
    "paragraphs": [
      "Morning count. Kira takes Hallway C: fifteen doors, fourteen occupied today. Fahim is back. She knocks two slow, one fast. He answers with one. She marks the sheet. The fluorescent hums its endless note. Somewhere on A-deck, a pipe knocks twice and stops, the way it has every morning for nine years.",
      "The lottery is at 0800. The council holds it in the mess, not the meeting room, because the mess has benches and therefore holds everyone who wants to watch. Nearly everyone wants to watch.",
      "Maya Strand sets the tin on the table. It's an actual tin — an old coffee tin, dented, from before. Everything in the bunker has a before.",
      "Three names go in for four slots. Because two hundred people and three names is what the arithmetic has come to. Nine years ago, the first lottery had one hundred and forty names in it. Now people have learned. They don't put their name in unless they mean it.",
      "Maya reaches into the tin without looking, the way someone does a thing they've done enough times to stop performing it.",
      "\"Jin Alvarez.\"",
      "Jin nods. He is already packed. He has been packed for three weeks.",
      "\"Kade Oshan.\"",
      "Kade doesn't react at all, which is how Lia knows he wanted it. Her father has spent ten years not reacting to things he wanted.",
      "Maya reaches in for the third name and stops. She looks at the paper in her hand for longer than she needs to.",
      "\"Lia Oshan.\"",
      "The mess gets very quiet, in the specific way a room goes quiet when two hundred people all decide at the same time not to look at something.",
      "Lia stands with the tomato prunings still in her apron pocket. She does not look at her father. She looks at Maya, and Maya — who has run this bunker through a decade of diminishing returns and has no illusions left about what a body can stand — looks back at her with something Lia doesn't have a word for.",
      "\"You put your name in,\" Kade says.",
      "\"Yes.\"",
      "\"Without telling me.\"",
      "\"Yes.\"",
      "\"You're seventeen.\"",
      "\"I'm the only person in this room who can tell a healthy plant from a dying one at twenty paces,\" Lia says. \"On the surface, in the dark, that's a skill. Underground, it's a hobby.\"",
      "Eugene Pryce watches from the back, standing because his hip won't take the benches anymore. Seventy-one years old and his memory comes and goes like a bad signal, but right now it's here, and it's telling him something about the third name being drawn.",
      "He goes back to his quarters after the meeting and pulls the box out from under the bunk. Thirty years of folding. He opens them on the floor and sorts them with hands that are still, thank God, steady.",
      "Launch facility, Level 1. Service corridors. The map he has never been able to find is the one for the northern grid, and he has been looking for nine years, and he is fairly sure the reason he can't find it is that it was never in this box.",
      "He sits on the floor among the paper and tries to remember whether he gave it to someone.",
      "Someone knocks. Two slow, one fast.",
      "\"Come in,\" Eugene says.",
      "Kira opens the door. She has her tally sheet folded in her hand and she holds it like a person holds something with writing on it they'd rather not read out.",
      "\"C-11,\" she says. \"Halloway.\"",
      "Eugene looks at the maps. \"How long?\"",
      "\"She didn't wake up. It was during the meeting.\" Kira's voice does the thing it does, which is nothing. \"Nobody heard.\"",
      "Fourteen occupied, this morning. Thirteen now. A slot has opened on the expedition roster that did not need to open, and the roster is full anyway, and the tin is empty, and somewhere above them — nine metres of concrete, then forty metres of ice, then the Shade — there is nothing at all.",
      "Eugene goes back to his maps."
    ]
  },
  {
    "id": 9,
    "timeline": 3,
    "timelineName": "The Floating City",
    "chapterNumber": 3,
    "title": "Twelve Degrees of Sun",
    "setting": "Concurrent — life inside the sunlight patch",
    "wordCount": 684,
    "paragraphs": [
      "The patch is twelve degrees wide today.",
      "Yorke knows this the way other people know their own pulse. She measured it at first light with the sextant and a stopwatch and the marker posts Kael welded to the eastern pontoons, and the number is twelve point one, down from twelve point four at the turn of the year, and the arithmetic of that decline is a thing she does not say out loud in council meetings because Reika has asked her not to frighten people with numbers they cannot use.",
      "She can use the numbers. That's the difference. She is the only one who can use the numbers.",
      "The deep nets come up heavy for the first time in eleven weeks. Taryn's vertical rigging worked: nets down forty metres on anchored cables, lifted by the crane they built out of trawler winches, and today they come up silver and thrashing, forty kilos, sixty, ninety — Nikos is shouting numbers from the deck of the *Ayia Marina* and Emiko Voss is laughing in a way that carries.",
      "One hundred and ten kilos. More than double the ration target. Enough to salt, enough to trade, enough to feed everyone for four days with leftovers.",
      "The whole eastern cluster comes out to watch the crane. Somebody bangs a wrench on a pot. Yuki Voss, fourteen, sits on a crate with her sketchbook and doesn't draw, just watches, which for Yuki is the highest compliment available.",
      "Dr. Seo-yun Park takes samples from the catch and logs them and spends the afternoon unhappy.",
      "\"What,\" Yorke says, at the evening council in Reika's lifeboat, tea in the mismatched cups.",
      "\"The catch wasn't one species. It was eleven species that don't school together.\" Seo-yun lays the tally on the table. \"They were running. Something pushed them up from below.\"",
      "\"Something like what?\"",
      "\"Cold water. A mass of it, coming up from the deep, deeper than the light reaches.\" Seo-yun taps her own chart, the one nobody wants to read. \"Or the top layer is thinning and the deep layer is rising to replace it. Which would mean the patch isn't just shrinking at the edges. It's shallowing.\"",
      "Reika pours more tea. That is Reika's answer to everything, and it has worked for nine years.",
      "\"So we caught a good day,\" Taryn says.",
      "\"So we caught a symptom,\" Seo-yun says.",
      "Yorke drinks her tea and does not say that she has known this for four months. She has known it since the panels started reading three percent low in the same week the water temperature dropped half a degree, and she hasn't said it because a thing said in a council meeting becomes a thing that has to be answered, and she doesn't have an answer.",
      "Tonight the plankton come up. This is the third night running. The water under the boats goes luminous and blue, drifting in long ropes of light that coil and uncoil with the swell, and people come out on the platforms and stand at the railings and look at it because it is beautiful and because there is nothing else to look at that isn't water or rope or another platform.",
      "Kael's crews have finished the first new structure off the salvaged eastern pontoons: a raised deck, six by four metres, on four lashed aluminium columns. Tomorrow they build the second. In six weeks they'll have a schoolhouse up there, off the damp, and the children will learn their letters eleven metres above the fish.",
      "Emiko asks her father, on the new deck, at night, with the plankton glowing below them: \"How long does it hold?\"",
      "Kael looks at the horizon where the light ends. Twelve point one degrees wide. Somewhere past it, the planet is a freezer. Here there is sun and fish and rope and eleven species of very frightened fish and a raised deck he built with his own hands and two daughters who have never known anything else.",
      "\"Long enough,\" he says.",
      "Emiko does not ask again. She is sixteen. She has already learned that the second question is the one that costs."
    ]
  },
  {
    "id": 10,
    "timeline": 1,
    "timelineName": "The Race",
    "chapterNumber": 4,
    "title": "The Corridor",
    "setting": "Near future — Earth races to escape",
    "wordCount": 663,
    "paragraphs": [
      "Kwame Osei had taken Baikonur with four hundred men and eleven trucks, and he had done it on a Tuesday, and by Friday the price of a seat to orbit had a number attached to it that anyone could look up.",
      "That was the part that frightened the world. Not the violence — there had been violence before, in Jakarta, in Lagos, over the water in the Sahel. The frightening part was the *pricing*. Kwame had put launch capacity on a market with published rates, tiered by mass and destination, with a discount for African nationals and a surcharge for anyone who had ever signed an Exodus Solutions contract.",
      "You cannot argue with a price. You can argue with a warlord. You can send peacekeepers. You cannot send peacekeepers to a spreadsheet.",
      "Amara watched the story break on a monitor in the fabrication hall while Yuki ran the third truss-layer deposition behind her and didn't look up.",
      "\"He's going to run out of rockets,\" Amara said.",
      "\"He's going to run out of fuel first,\" Yuki said, still not looking up. \"The pad's fine. The pad's always been fine. There are eleven Soyuz-class airframes in storage at Site 31 and none of them can get to a transfer orbit without twelve hundred tonnes of kerolox that he doesn't have and can't make. He's selling something he can't deliver.\"",
      "Amara turned around slowly.",
      "\"How do you know what's in storage at Site 31?\"",
      "Yuki's hands kept moving on the control panel. A pause, a beat too long. \"It's in the public procurement filings. Kazakhstan published the disposal inventory in 2031.\"",
      "That was true. Amara had read the same filing. She had not remembered a single line of it, and Yuki had not needed to look it up.",
      "Riko arrived at 1900 with a folder and no greeting, which Amara was beginning to understand was Riko's entire mode of address.",
      "\"Twelve people on your team are on a list,\" Riko said. \"I need you to sign off on moving four of them.\"",
      "\"A list of what?\"",
      "\"People who've been in contact with FreeLight Collective.\" Riko put the folder on the bench. It was thin. It was thinner than Amara expected. \"Chen Wei's people have been posting your spec to relay nodes all week. Somebody on your floor is feeding them.\"",
      "\"Then find the somebody. Don't move four people who haven't done anything.\"",
      "\"Two of the four have done something.\" Riko's face did not change. \"One of them is Yuki Sato.\"",
      "Amara did not look at Yuki. This was, she would think later, the first real decision she made in that facility — and she made it in a quarter of a second, by not looking, and she has never been sure whether it was loyalty or cowardice.",
      "\"No,\" Amara said.",
      "\"It's not a request.\"",
      "\"You need her. You have six months and a chalk drawing and no one else on this site has read my Methods section closely enough to catch it when I'm wrong.\" Amara closed the folder. \"If you take her off this floor, you take four months with her. Tell Garrett that. Tell him I said it in those words.\"",
      "Riko stood there for a moment. Then she took the folder back.",
      "\"For what it's worth,\" Riko said, at the door, \"I didn't put her on the list. Somebody else did. Somebody with access to her traffic.\"",
      "\"Who?\"",
      "\"That's the part I'm still working on.\"",
      "She left. Behind Amara, the deposition rig ran its long hiss, layer on layer, graphene settling onto a truss the length of a football field.",
      "Yuki Sato stayed on the floor until 0300 that night and went over the rail section tolerances twice, and found an error both times, and never once mentioned the folder, and never once looked at Amara as if she owed her anything.",
      "That was the second decision, and Yuki made it, and Amara didn't know for four more months what it had cost."
    ]
  },
  {
    "id": 11,
    "timeline": 2,
    "timelineName": "The Bunker",
    "chapterNumber": 4,
    "title": "The Northern Grid",
    "setting": "Years after the Shade — survivors underground",
    "wordCount": 552,
    "paragraphs": [
      "Eugene Pryce has been awake for thirty hours and he is aware that this is the kind of thing Dr. Voss would sit him down about, gently, in the way she sits everyone down about everything, because she has been managing the bodies and minds of two hundred people for a decade and has no more patience for heroics in the old.",
      "He is not being heroic. He is looking for a map.",
      "The trick is that he remembers the map. He remembers the north corridor as a physical thing — the smell of it, the taste of the air, cold metal and cured rubber and the ghost of a coffee someone spilled in 2031. He remembers the map as an object: a laminated sheet, A2, with the northern grid drawn in green because the northern grid was secondary power.",
      "He remembers holding it. He remembers that it was not in the box.",
      "He gets up and goes to the archive room.",
      "The archive is two hundred and twelve boxes of the before-times, catalogued by Maya with a system that made sense in year two and has been unravelling ever since. Eugene tells himself he is doing useful work. This is not true even a little. He is doing what a man does when his own memory has become a room he keeps walking into and finding rearranged.",
      "Maya is there at 0400 with a mug and no questions. That is what she is for.",
      "\"Northern grid,\" Eugene says.",
      "\"Secondary power routing. Site 44, I think.\" Maya finds the box on the second try. \"Disposal survey, yes. Wait.\"",
      "She pulls out the laminated sheet. A2. Green lines. The northern grid, complete, with three service corridors converging on a chamber marked LAUNCH FACILITY — AUXILIARY OBSERVATION, and beside it a number that no one has looked at in ten years, six digits and a hyphen, the way rocketry people write dates.",
      "\"Is that a...\" Eugene can't finish it.",
      "\"It's a date,\" Maya says.",
      "\"May 2032.\" He has to sit down. \"That's ten years ago. That's *after*.\"",
      "\"After what?\"",
      "\"After the Shade fell.\" Eugene's hands are shaking so hard the lamination clatters. \"Maya. This survey was filed in 2032. Two years after the panels closed. Somebody walked that corridor, drew it, and filed it, and nobody ever sent a team, because nobody ever opened this box.\"",
      "Maya sets down her mug very carefully, because she is the kind of person who, on receiving news that changes everything, first prevents a spill.",
      "\"Who filed it?\"",
      "Eugene looks at the bottom right corner of the sheet, at the approval block, at the initials in the box. Two letters. He does not need to look them up.",
      "\"Me,\" he says.",
      "He does not remember doing it. He remembers the smell of the corridor. He does not remember drawing the sheet that has been under his bunk for nine years.",
      "Eugene sits in the archive room and cries, briefly and without drama, the way old men cry, with his mouth shut. Maya lets him. Then she takes the map, and puts it in her coat, and goes to find Kade Oshan, because the expedition leaves tomorrow and the roster still has four names on it and there is now a fifth thing on the surface worth walking toward."
    ]
  },
  {
    "id": 12,
    "timeline": 3,
    "timelineName": "The Floating City",
    "chapterNumber": 4,
    "title": "What the Storm Brings",
    "setting": "Concurrent — life inside the sunlight patch",
    "wordCount": 740,
    "paragraphs": [
      "The storm comes on the ninth day.",
      "Yorke has four hours' warning from the barometer and the colour of the sky, which is enough to save the array if she acts immediately and enough to save nothing else. She is on the solar platform at 0500, throwing breakers, folding the western wing down onto the deck, and shouting at the fishing cluster through a bullhorn while Emiko Voss and four others lash the deep-net winches.",
      "The squall line hits at 0930. It is not a big storm by the standards of the world before — force eight at most — but in a floating city of welded pontoons it is the closest thing to a siege. The swell comes through the gaps where the eastern cluster used to be, because the eastern cluster was dismantled for Taryn's nets, and the water that used to be blocked by pontoons now has a road inland.",
      "Four platforms take damage. Two houseboats come loose and have to be cut free to save the dock. A section of the new raised deck — thirty days of Kael's work — goes into the sea at 1140 and does not come back.",
      "Nobody dies. This is reported at the evening council as a triumph, and it is one, and everyone in the lifeboat knows how narrow the margin was.",
      "The council meets at 1900 in a space that is now too small, because sixty boats have become fifty-eight and the tolerances have closed.",
      "Hao Zhang, the desalination engineer, brings the survey. Forty of the eastern pontoons were dismantled to build net rigging and the raised deck. Seventeen of them are now at the bottom of the sea. The city has lost eleven percent of its structural margin to buy itself ninety kilograms of fish a day.",
      "\"We can replace the pontoons,\" Kael says.",
      "\"With what?\" Hao asks. He is not a confrontational man. He is a man who has spent nine years turning seawater into drinking water and has developed the particular bleakness of people whose job is volume. \"Every kilogram of aluminium in this city is already in use. There is no depot. There is no mainland to drive to. The only material we have is the material we are standing on.\"",
      "\"Then we rebuild smaller and stronger,\" Kael says. \"Less deck, more hull.\"",
      "\"That's the same trade as before,\" Reika says.",
      "\"It's the *reverse* of the trade as before,\" Kael says. \"We got fat on surface area for nine years. We built up because up was cheap. It was only cheap because we had margin. We don't have margin anymore.\"",
      "Dr. Seo-yun Park has said nothing for the whole meeting, which is how the room knows she is about to.",
      "She opens her log and reads out the anomaly list: water temperature down one point one degrees over nine months, eleven species pushed up from the deep, plankton blooms on three consecutive nights, and — as of the last four days — the dawn measurement of the patch, taken from the marker posts Kael welded to the east, which has gone from twelve point one degrees to eleven point six.",
      "The tea goes cold in the mismatched cups.",
      "\"Two degrees a year,\" Seo-yun says. \"At the current rate, the patch closes in six years. Not shrinks. *Closes.*\"",
      "Reika pours, out of reflex, and stops halfway, because for the first time in nine years there is nobody in the room reaching for a cup.",
      "After the meeting, Yorke stands on the central barge with Kael, looking east, where the black starts.",
      "\"I've known for four months,\" she says.",
      "\"I know,\" Kael says.",
      "\"You didn't say anything.\"",
      "\"You're the one who's never wrong about the numbers.\" He shrugs. \"I figured if you weren't saying it, there was a reason, and the reason was that saying it wouldn't help. Was there a reason?\"",
      "\"Yes,\" Yorke says. And then, because the storm has taken the raised deck and the margins and her last reserve of patience for the polite version: \"There is a hole in the sky, Kael. Six years from now it's a lid. And we have fifty-eight boats and a desalination plant and a school we hadn't finished building. There's nothing to *do*.\"",
      "Kael looks at the water for a while.",
      "\"There's never nothing to do,\" he says. \"There's just the thing you don't want to do yet.\"",
      "[Continue with Chapters 3-20 for all three timelines...]"
    ]
  }
]

export const totalChaptersPlanned = 60

export const plannedPerTimeline = 20
