// All written chapters of "The Shade"
// Interleaved reading order: T1-Ch1, T2-Ch1, T3-Ch1, T1-Ch2, T2-Ch2, T3-Ch2

export const chapters = [
  {
    id: 1,
    timeline: 1,
    timelineName: 'The Race',
    chapterNumber: 1,
    title: 'The Signal',
    setting: 'Near future — Earth races to escape',
    paragraphs: [
      `The dust hung in the server room air. Amara Okafor wiped sweat from her forehead, left a streak of thermal paste across her temple. The cooling system had failed again. Sixteen hours into the shift and the Helios Array simulation still wouldn't converge.`,
      `Her terminal blinked. Priority alert. She almost ignored it—another false alarm, another asteroid that would miss by comfortable margins. But the encryption signature was wrong. Observatory-direct. She opened it.`,
      `2034-Prometheus. Impact probability: 94.7%. Time to collision: 47 months.`,
      `The numbers sat there. Clean. Certain. She ran the trajectory three times. Each iteration tightened the certainty. The asteroid measured 2.4 kilometers across. Strike point: North Atlantic. The simulation showed the pressure wave, the tsunami, the dust cloud that would follow.`,
      `Her hands shook. She reached for the phone, stopped. Who to call first? Her supervisor worked for Garrett Voss. Exodus Solutions funded this lab, owned the Helios Array, owned her research. The man who'd promised to save humanity would want this first.`,
      `The server fans screamed. One failed. Then another. The room temperature spiked. Amara barely noticed.`,
      `Outside the lab window, the city kept moving. Cars threaded through traffic. Someone walked a dog. The sun hung in a sky that would soon fill with enough debris to end most life on the surface.`,
      `She thought: I built salvation. The Array could power the evacuation ships, capture and store solar energy for the colonies we'd build in orbit and beyond. Four years of my life. But Garrett controls it.`,
      `The phone rang. She hadn't called anyone yet. The screen showed: UNKNOWN.`,
      `She answered.`,
      `"Dr. Okafor." A woman's voice, flat affect. "You have the trajectory data."`,
      `"Who is this?"`,
      `"Someone who knows what Garrett Voss plans to do with your Array. And what you need to do to stop him."`,
      `The line went dead.`,
      `Through the window, a military helicopter crossed the skyline. Then another. Already? The data wasn't public yet. How long had they known?`,
      `Amara looked at her screen. The Helios Array blueprint, three years of engineering compressed into lines and equations. Meant to save everyone. But Garrett would save only those who could pay.`,
      `Her terminal chimed. Email from Garrett's office: Emergency board meeting, 0600 tomorrow. Attendance mandatory.`,
      `She thought about the caller. About stopping Garrett. She'd built the Array believing in its purpose. Now she had to decide: trust the man who paid for it, or the stranger who warned her?`,
      `The last server fan died. Red lights across the board. In four years, none of this would matter. The rock was coming. Everything else was just the scramble before impact.`,
    ],
  },
  {
    id: 2,
    timeline: 2,
    timelineName: 'The Bunker',
    chapterNumber: 1,
    title: 'Ten Years Down',
    setting: 'Years after the Shade — survivors underground',
    paragraphs: [
      `Kira walks the morning count. Hallway C, fifteen doors. Thirteen occupied. She knocks: two slow, one fast. Waits for the knock back. At C-7 no answer. She knocks again. Counts thirty seconds by her pulse. The door opens. Fahim's eyes are red-rimmed, but he's standing. That's what matters. She marks the tally sheet and moves on. Overhead, the fluorescent hums its endless note.`,
      `Ten years since the Shade fell. The bunker marks time in reactor cycles and shift rotations. Morning is when the lights come up. Night is when they dim to emergency levels. The sun is a story Eugene tells to children who've never seen it.`,
      `Dr. Amara Voss checks the reactor gauges. Coolant temperature steady. Pressure nominal. The nuclear plant was meant to power a launch facility for five years. They've stretched it to ten. Every year she finds new ways to cannibalize non-essential systems. Every year the margin shrinks.`,
      `The hydroponic bay smells like growth and rot together. Lia Oshan tends the tomato vines, checking each plant for blight. Seventeen and she's never tasted fruit grown in soil. Never felt rain. The garden feeds two hundred people on a rotation of greens and root vegetables. When a crop fails, people go hungry. No one complains. Complaining uses energy.`,
      `Maya Strand calls the council meeting for 0800. Same room, same faces, same arguments worn smooth by repetition. The expedition lottery is next week. Four people will suit up, take thermal gear and emergency rations, and walk into the frozen dark for four hours. The protocol is strict: stay within beacon radius, return before core temperature drops below 35 Celsius. Three expeditions this year. Three times they've returned with nothing.`,
      `Kade Oshan wants to push farther. His daughter hasn't seen the sky. He'll die trying to find it.`,
      `Eugene Pryce remembers the before. Shuttle technician, sixty years old when the Shade fell. Now seventy-one and his memory frays at the edges. Sometimes he confuses yesterday with a decade ago. But he remembers the launch facility, the corridors that run beyond the bunker's sealed sections. Old maps folded in his quarters. He spreads them for anyone who'll listen.`,
      `The reactor hums. The lights flicker once, stabilize. Another day in the bunker. Another count. Another shift. The world outside is −60 Celsius and absolute dark. Inside, the walls are close and warm and certain. Some call it survival. Others call it a tomb they haven't finished dying in.`,
      `Kade watches his daughter in the garden and thinks: there has to be more than this.`,
    ],
  },
  {
    id: 3,
    timeline: 3,
    timelineName: 'The Floating City',
    chapterNumber: 1,
    title: 'Harbor of Boats',
    setting: 'Concurrent — life inside the sunlight patch',
    paragraphs: [
      `Mira surveys the floating city at dawn. The sun rises over water that reflects gold and orange, and for a moment she forgets how small their refuge is. Sixty boats lashed together, makeshift platforms bridging the gaps. Five hundred people living on what used to be personal watercraft, fishing vessels, a houseboat cluster, two cargo barges. They've added structures—bamboo frames, salvaged aluminum, rope bridges strung between hulls.`,
      `The geostationary patch sits over deep ocean. Forty kilometers of open water lit by sun while the rest of the planet freezes in perpetual twilight. They were lucky. Or doomed to watch the light shrink while they cling to it.`,
      `She climbs to the highest platform. Kael's construction, built from shipping containers welded to the central barge. From here she can see the whole city: the eastern fishing cluster, the western living quarters, the central market where people trade catch for repairs. Beyond, the water darkens. The edge of the light.`,
      `Nets go out with the morning. Yorke watches from her solar platform, checking the array output. Mismatched panels salvaged from boats, angled to catch every degree of sun. Power charges batteries for the water purification system, for lights when the sun sets, for tools. She's optimized the arrangement twelve times. Each iteration buys them a few more watt-hours per day.`,
      `Kael's daughters help with the nets. Emiko, sixteen, has modified the pulleys with reclaimed bicycle gears. Yuki, fourteen, sketches the fish they catch, building an inventory of what lives in this warm pocket of ocean. Dr. Seo-yun encourages her, teaches her to notice patterns. Which species are thriving, which are disappearing. The water temperature dropped half a degree last month.`,
      `Nikos brings in the morning catch. His trawler is the oldest vessel, Greek letters fading on the hull. He's been fishing these waters since the Shade fell, back when they thought rescue would come. Now he teaches younger crews to read currents and weather. The old ways adapted to a new world where the only sky is a circle overhead.`,
      `Council meets at noon in Reika's lifeboat. She pours cold tea from a thermal jug, serves it in mismatched cups. The agenda: food stores, water rations, a proposal to expand the platform eastward. Kael wants to build up. Others want to stay low, keep weight distributed. Every decision is about survival measured in stability and fish and sunlight.`,
      `The city rocks gently on the swell. At night, bioluminescent plankton glow beneath the boats. Small beauty in a dying ocean. Mira watches the horizon where the light meets dark. Somewhere beyond, the planet freezes. Here, for now, they fish and build and hope the warmth holds.`,
    ],
  },
  {
    id: 4,
    timeline: 1,
    timelineName: 'The Race',
    chapterNumber: 2,
    title: 'Launch Windows',
    setting: 'Near future — Earth races to escape',
    paragraphs: [
      `The UN General Assembly hall held 193 nations. Garrett Voss counted twelve that mattered.`,
      `He sat in the gallery, watching them argue over protocols for joint evacuation. As if protocols would save anyone. The Chinese delegation demanded equal launch capacity. The Americans countered with historical investment figures. The Europeans proposed a lottery system. All of them pretended the math could be democratic.`,
      `Launch capacity was finite. The asteroid wasn't.`,
      `Garrett's tablet showed the real numbers. Current orbital infrastructure: 940 personnel capacity across all active stations. Launch windows to viable trajectories: 87 in the next 47 months. Each window narrowed as fuel calculations tightened. By month 40, you'd need three times current fuel stocks to reach orbit with enough delta-v to escape the debris field.`,
      `He ran the simulation again. Best case, full global cooperation, every spaceport running continuous missions: 12,000 people off-planet before impact. Earth population: 8.3 billion.`,
      `Someone had to choose. Garrett preferred it be him rather than some committee that would spend six months debating selection criteria while launch windows closed.`,
      `His phone buzzed. Text from Riko: SITUATION BAIKONUR. CALL NOW.`,
      `He stepped into the hallway. The call connected before the first ring.`,
      `"Kwame Osei took the Cosmodrome." Riko's voice had that clipped quality she used when things had gone badly. "Four hours ago. His forces came overland, avoided sat coverage. They control the main pad and fuel depot."`,
      `Garrett felt his pulse level. Stay ahead of the chaos or get swept under. "Casualties?"`,
      `"Thirty confirmed. Mostly ground crew. The launch director negotiated a ceasefire."`,
      `"Tell me you have forces en route."`,
      `"Six hours out. But Kwame's already broadcasting. Says launch capacity is African first, then whoever can pay. He's set up a market."`,
      `Of course he had. The warlord prophet, turning the apocalypse into a trading floor.`,
      `Garrett thought about the Helios Array sitting in Amara's lab. With that operational, he could power ships ten times faster than conventional systems. But the Array was still theoretical. And now Kwame controlled one of the few pads capable of heavy-lift launches.`,
      `"Hold position," he told Riko. "Don't engage until I give the word."`,
      `"He's fortifying. Every hour we wait—"`,
      `"I know. But if we take it by force, the pad gets damaged. We need it intact."`,
      `He ended the call. Through the window, the UN delegates were voting on a resolution to establish an Evacuation Coordination Committee. Twelve nations had to approve. The vote would take days. By then Kwame would own the primary route to orbit.`,
      `Garrett made three calls. The first to his logistics chief: move the Exodus Solutions fleet to staging range of Baikonur. The second to his intel director: find out what Kwame wanted that money couldn't buy. The third to Amara.`,
      `"Dr. Okafor. Have you seen the news from Kazakhstan?"`,
      `"I saw." Her voice carried that controlled anger she used when someone wasted her time. "What do you want, Garrett?"`,
      `"How long until the Array is operational?"`,
      `Silence. Then: "With full funding and no regulatory delays? Eighteen months."`,
      `"You have six."`,
      `"That's not possible."`,
      `"Make it possible. I'll triple your budget, clear every regulatory barrier, and put you in direct control. No board approval needed. But I need that Array working in six months."`,
      `Another pause. He could almost hear her calculating. "Why the rush? We have four years before impact."`,
      `"Because in four years everyone with a ship will be fighting over fuel. But if I have the Array, I control the energy supply. And whoever controls energy controls who gets off this rock."`,
      `"You want me to weaponize my research."`,
      `"I want you to save lives. Mine. Yours. Everyone who works for Exodus. We can coordinate a real evacuation, not the chaos that's coming. But only if we move now."`,
      `He could hear her breathing. The idealist and the pragmatist fighting it out behind her silence.`,
      `"I'll need your head engineer," she said finally. "And complete access to your fabrication facilities."`,
      `"Done. I'm sending Riko to escort you to the secure site. Pack for six months."`,
      `He hung up and looked back through the window at the UN floor. The vote was still going. Procedure grinding forward while the world burned. Some of them would make it off-planet. Garrett would see to that. The rest would learn that survival had never been democratic.`,
      `His tablet chimed. News alert: Armed conflict at Baikonur Cosmodrome. At least thirty dead. Kazakh government requests international peacekeeping force.`,
      `Too late for peacekeeping. The war for tomorrow had started.`,
    ],
  },
  {
    id: 5,
    timeline: 2,
    timelineName: 'The Bunker',
    chapterNumber: 2,
    title: 'The Surface Protocol',
    setting: 'Years after the Shade — survivors underground',
    paragraphs: [
      `Marcus suits up in the equipment bay. Thermal gear, oxygen reserve, emergency beacon. The protocol is twenty years old but nobody's improved it. Four hours maximum exposure. Stay within a two-kilometer radius. Return before core temperature drops below 35 Celsius.`,
      `He's done this seventeen times. Seventeen expeditions into the frozen dark. Seventeen times he's returned with nothing.`,
      `The team assembles: four people, two sleds loaded with gear. Jin checks the beacon calibration. Kade watches from the observation window, his daughter beside him. Lia's never been topside. None of the children born after the Shade have.`,
      `Dr. Amara Voss runs through the final checklist. Reactor output stable. Life support nominal. The outer door will cycle in sixty seconds. She marks the departure time on her log.`,
      `The door opens. Cold floods in, −62 Celsius, the air crystallizing in visible clouds. Marcus steps through. His headlamp cuts a cone of light through absolute darkness. No stars. No moon. The Shade blocks everything.`,
      `The ground is ice over permafrost. His boots crunch. The sled runners scrape. They move northwest, following a heading Jin calculated from old maps. There might be a highway under the ice. There might be nothing.`,
      `Two kilometers out, they stop. Jin takes readings. Temperature, wind speed, atmospheric composition. All within expected ranges. The darkness is total beyond their lights. Marcus thinks: somewhere above us, solar panels cover the sky. Somewhere there's a hole with sunlight. But not here.`,
      `They find a building. Collapsed roof, walls buckled by ice. They clear the entrance, work their way inside. Storage facility, long abandoned. Shelves empty. No fuel, no food, no equipment worth salvaging.`,
      `Back outside, Jin marks the location on his map. Another nothing. Another empty square on the growing chart of the frozen world.`,
      `Three hours in, Marcus's core temperature reads 36.1. The protocol is clear: turn back. But there's a ridge to the north, maybe a thermal anomaly, maybe just wind patterns. He wants to check.`,
      `Jin shakes his head. The protocol. They turn back.`,
      `The bunker door cycles. Warm air, bright lights. They strip the gear, run the decontamination sequence. Amara logs their return. Four hours, twelve minutes. No casualties. No discoveries.`,
      `Maya asks for the report at the evening council meeting. Jin spreads his map. Seventeen expeditions, thirty-four sorties, coverage area expanding but still finding nothing. The frozen dark goes on.`,
      `Eugene watches from the back. He's been thinking about the launch facility, the parts they sealed off when the population concentrated in the bunker core. There are tunnels. Old service routes. He's got maps, somewhere in his quarters, if he can remember where.`,
      `Kade asks about the next lottery. Who goes topside next week. The protocol allows expeditions every seven days, resource recovery permitting.`,
      `Lia sits in the hydroponic bay after the meeting. The tomatoes need pruning. The system cycles, water and nutrients flowing through channels, LED arrays providing spectrum. It's all closed-loop, all balanced. It works. But she understands what her father chases: the world outside this metal shell. The sun he talks about. The open air.`,
      `She's seventeen. She's never seen a sky.`,
    ],
  },
  {
    id: 6,
    timeline: 3,
    timelineName: 'The Floating City',
    chapterNumber: 2,
    title: "The Engineer's Gambit",
    setting: 'Concurrent — life inside the sunlight patch',
    paragraphs: [
      `Yorke climbs the solar platform at first light. The array needs realignment—yesterday's output dropped three percent. Small losses compound. Three percent today means someone goes thirsty tomorrow.`,
      `The panels tilt on salvaged hinges, tracking mechanisms jury-rigged from boat winches. She adjusts the western section by hand, checking voltage as she works. The morning sun is perfect, low angle, no clouds in this pocket of sky. But the patch is smaller than last year. She's measured it.`,
      `Below, the fishing nets come up. Kael's daughters help haul, Emiko calling out the rhythm. The catch looks thin. Yorke notes it—fish populations correlating with water temperature, temperature dropping monthly. Dr. Seo-yun has the data. Nobody wants to see the trend line.`,
      `Council meets at noon. Reika pours tea, serves it in the mismatched cups they've used for three years. The agenda: Taryn's proposal to expand deep-water harvesting.`,
      `"We dismantle the eastern pontoons," Taryn says. "Use the materials for vertical nets. Go deeper where the fish are moving."`,
      `"You're asking us to cannibalize the city," someone says.`,
      `"I'm asking us to adapt."`,
      `The debate runs for an hour. Resources versus risk. Stability versus survival. Finally a vote: thirteen for, eight against. The expansion proceeds.`,
      `Kael's team starts work the next day. They unbolt aluminum frames, coil the anchor lines, strip the decking. Piece by piece, the eastern edge of the city comes apart. Each beam, each sheet of metal gets marked and inventoried. Everything has two futures: what it was, what it might become.`,
      `By evening, a gap opens in the city. Water shows between the remaining platforms. It feels like amputation.`,
      `Yorke watches from her solar platform. The math is simple: fewer surface structures means less electrical load. But it also means less living space, less storage, less buffer when storms hit. They're trading stability for food. She hopes the trade is worth it.`,
      `Nikos brings his trawler in after dark. He ties off at the central dock, climbs aboard with his catch log. The numbers are down again. Forty kilos today. They need eighty to meet rations.`,
      `"The cold's pushing them deeper," he tells Seo-yun. "Below where we can reach safely."`,
      `"Then we learn to reach deeper."`,
      `"Or we eat less."`,
      `That night, Yorke lies in her cabin—a repurposed houseboat room, four meters by three, everything she owns within arm's reach. Through the porthole, she can see the edge of darkness where the light ends. Out there, the planet freezes. Here, for now, the sun holds.`,
      `She thinks about the solar array, about the slow decline in output as the patch shrinks. She's extended the system twice, optimized every connection. But you can't engineer around geometry. Less sunlight means less power. Less power means choices she doesn't want to make.`,
      `Tomorrow she'll recalibrate. Tomorrow the nets will go deeper. Tomorrow Kael's team will weld the salvaged metal into new structures, building from what they've dismantled. Adapting. Always adapting.`,
      `The city rocks on the swell. Somewhere below, in the dark water, fish are moving. Somewhere above, the Shade holds. And in this thin margin between, five hundred people try to hold on.`,
    ],
  },
]

export const totalChaptersPlanned = 60
